### ISSUE TITLE
Couldn't find the css class for placeholder text color

### ISSUE THREAD

**Issue by Mokin711** [tbleckert/react-select-search#197]
I am looking for the css class that is responsible for styling the placeholder text in search, specifically the color. I went to the style.css and tried every single class provided but none of them seemed to work.

**Comment by tbleckert** [comment]
Hi @Mokin711 ! If you use the built-in components, you can change the placeholder color with:

```css
.select-search__input::placeholder {
    color: red;
}
```
