### ISSUE TITLE
Select doesn't close on click to it 

### ISSUE THREAD

**Issue by TonyCh55** [tbleckert/react-select-search#242]
When click on select it opens and when to click it again it doesn't close

**Comment by adiled** [comment]
Anyone facing this, remove `multiple` option form your props, and also make sure if you're using a custom `renderOption`, the first parameter is props that you need to forward like so:
``` jsx
renderOption={(props, optionData, { highlighted, selected }) => <li {...props}>...</li>}
```

**Comment by fmmajd** [comment]
For anyone else having the same problem in the future, it's not a js issue. it's a CSS issue. You can add this to have "close on blur" functionality:
```css
.form-group-container:not(.form-group-has-focus) .form-group-select {
  display: none;
}
```

**Comment by CallumJHays** [comment]
To add to @fmmajd 's answer, to get this working with css modules, you need to supply definitions for the classes `.has-focus` and `.select`, even if empty.
```css
/* yourReactSelectSearch.module.css */

/* required even if empty, otherwise classnames are never assigned */
.container {}
.has-focus {}
.select {}

.container:not(.has-focus) .select {
    display: none;
}
```

It appears that the example default `style.module.css`, as well as [the example storybook site](https://react-select-search.com) is out-of-date.
